# Taller Práctico de Análisis de Datos con Pandas

## Flota de Transporte y Envíos Logísticos

In [82]:
import pandas as pd

## 1. Lectura y estructura base

In [83]:
# Importar el DataFrame desde el archivo envios_transporte.csv
df_envios = pd.read_csv("envios_transporte.csv")
df_envios

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.0,14.0,16.32,A Tiempo
1,LOG-4002,Armenia,Camioneta,Textiles,120.0,70.0,17.90,A Tiempo
2,LOG-4003,Ibagué,Camión Mediano,Alimentos,78.5,22.0,5.64,A Tiempo
3,LOG-4004,Pereira,Camioneta,Textiles,NaN,14.0,7.96,A Tiempo
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.0,14.0,11.01,A Tiempo
...,...,...,...,...,...,...,...,...
1007,LOG-4068,Armenia,Camión Mediano,Electrónica,78.5,52.0,4.77,Cancelado
1008,LOG-4069,Ibagué,Tractomula,Textiles,450.0,35.5,23.57,A Tiempo
1009,LOG-4070,Ibagué,Camioneta,Alimentos,45.0,22.0,13.33,Retrasado
1010,LOG-4071,Cali,Tractomula,Materiales Construcción,260.0,8.5,4.62,Cancelado
1011,LOG-4072,Manizales,Camión Mediano,Alimentos,180.5,14.0,12.91,A Tiempo

## 2. Proyección y separación de series

In [84]:
# Extrae la columna Tipo_Vehiculo como una Serie de pandas
tipo_vehiculo = df_envios["Tipo_Vehiculo"]
tipo_vehiculo, type(tipo_vehiculo)

(0       Camión Mediano
 1            Camioneta
 2       Camión Mediano
 3            Camioneta
 4           Tractomula
              ...
 1007    Camión Mediano
 1008        Tractomula
 1009         Camioneta
 1010        Tractomula
 1011    Camión Mediano
 Name: Tipo_Vehiculo, Length: 1012, dtype: str,
 pandas.Series)

In [85]:
# DataFrame reducido que presente las columnas Ruta_Origen, Tipo_Carga y Distancia_KM
df_reducido = df_envios[["Ruta_Origen", "Tipo_Carga", "Distancia_KM"]]
df_reducido

     Ruta_Origen               Tipo_Carga  Distancia_KM
0         Ibagué              Electrónica         120.0
1        Armenia                 Textiles         120.0
2         Ibagué                Alimentos          78.5
3        Pereira                 Textiles           NaN
4        Pereira  Materiales Construcción         120.0
...          ...                      ...           ...
1007     Armenia              Electrónica          78.5
1008      Ibagué                 Textiles         450.0
1009      Ibagué                Alimentos          45.0
1010        Cali  Materiales Construcción         260.0
1011   Manizales                Alimentos         180.5

[1012 rows x 3 columns]

## 3. Acceso por etiqueta (loc)

In [86]:
# Mostrar la informacion completa del despacho registrado en la fila con índice 99 utilizando el método .loc[]
despacho_99 = df_envios.loc[99]
despacho_99

ID_Envio                 LOG-4100
Ruta_Origen             Manizales
Tipo_Vehiculo          Tractomula
Tipo_Carga              Alimentos
Distancia_KM                120.0
Combustible_Galones           NaN
Peso_Toneladas               9.72
Estado_Entrega           A Tiempo
Name: 99, dtype: object

## 4. Limpieza de registros duplicados

In [87]:
# Eliminar todos los registros duplicados
print("Filas antes:", len(df_envios))
print("Duplicados encontrados:", df_envios.duplicated().sum())

df_sin_duplicados = df_envios.drop_duplicates()

print("Filas después:", len(df_sin_duplicados))

df_sin_duplicados

Filas antes: 1012
Duplicados encontrados: 12
Filas después: 1000

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.0,14.0,16.32,A Tiempo
1,LOG-4002,Armenia,Camioneta,Textiles,120.0,70.0,17.90,A Tiempo
2,LOG-4003,Ibagué,Camión Mediano,Alimentos,78.5,22.0,5.64,A Tiempo
3,LOG-4004,Pereira,Camioneta,Textiles,NaN,14.0,7.96,A Tiempo
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.0,14.0,11.01,A Tiempo
...,...,...,...,...,...,...,...,...
995,LOG-4996,Armenia,Tractomula,Electrónica,450.0,14.0,1.01,A Tiempo
996,LOG-4997,Pereira,Camioneta,Electrónica,260.0,14.0,2.03,A Tiempo
997,LOG-4998,Ibagué,Camioneta,Alimentos,78.5,52.0,20.68,Retrasado
998,LOG-4999,Manizales,Furgón,Textiles,180.5,22.0,21.51,A Tiempo
999,LOG-5000,Ibagué,Tractomula,Materiales Construcción,45.0,8.5,12.79,Retrasado

## 5. Filtrado por condición simple

In [88]:
# Filtrado por condición simple: despachos con más de 15 toneladas
df_carga_pesada = df_sin_duplicados[df_sin_duplicados["Peso_Toneladas"] > 15.0]

print("Despachos con más de 15 toneladas:", len(df_carga_pesada))

df_carga_pesada

Despachos con más de 15 toneladas: 415

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.0,14.0,16.32,A Tiempo
1,LOG-4002,Armenia,Camioneta,Textiles,120.0,70.0,17.90,A Tiempo
7,LOG-4008,Ibagué,Camioneta,Alimentos,180.5,NaN,21.94,A Tiempo
10,LOG-4011,Manizales,Furgón,Textiles,120.0,14.0,22.03,A Tiempo
14,LOG-4015,Cali,Camión Mediano,Alimentos,120.0,22.0,21.68,Cancelado
...,...,...,...,...,...,...,...,...
985,LOG-4986,Pereira,Tractomula,Alimentos,120.0,22.0,18.43,Retrasado
991,LOG-4992,Armenia,Camión Mediano,Materiales Construcción,120.0,NaN,22.40,A Tiempo
992,LOG-4993,Cali,Camioneta,Textiles,78.5,14.0,21.18,A Tiempo
997,LOG-4998,Ibagué,Camioneta,Alimentos,78.5,52.0,20.68,Retrasado
998,LOG-4999,Manizales,Furgón,Textiles,180.5,22.0,21.51,A Tiempo

## 6. Filtrado categórico con .isin()

In [89]:
# Filtrar por tipo de vehiculo (isin)
df_vehiculos = df_sin_duplicados[df_sin_duplicados["Tipo_Vehiculo"].isin(["Tractomula", "Camión Mediano"])]
df_vehiculos

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.0,14.0,16.32,A Tiempo
2,LOG-4003,Ibagué,Camión Mediano,Alimentos,78.5,22.0,5.64,A Tiempo
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.0,14.0,11.01,A Tiempo
5,LOG-4006,Cali,Tractomula,Electrónica,180.5,70.0,7.96,A Tiempo
9,LOG-4010,Pereira,Camión Mediano,Electrónica,78.5,8.5,10.56,Retrasado
...,...,...,...,...,...,...,...,...
985,LOG-4986,Pereira,Tractomula,Alimentos,120.0,22.0,18.43,Retrasado
991,LOG-4992,Armenia,Camión Mediano,Materiales Construcción,120.0,NaN,22.40,A Tiempo
994,LOG-4995,Ibagué,Camión Mediano,Textiles,120.0,52.0,3.10,A Tiempo
995,LOG-4996,Armenia,Tractomula,Electrónica,450.0,14.0,1.01,A Tiempo
999,LOG-5000,Ibagué,Tractomula,Materiales Construcción,45.0,8.5,12.79,Retrasado

## 7. Filtrado de rangos numéricos (between)

In [90]:
# Filtrar las rutas con Distancia_KM entre 100.0 y 250.0
df_distancia = df_sin_duplicados[df_sin_duplicados["Distancia_KM"].between(100.0, 250.0)]
df_distancia

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.0,14.0,16.32,A Tiempo
1,LOG-4002,Armenia,Camioneta,Textiles,120.0,70.0,17.90,A Tiempo
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.0,14.0,11.01,A Tiempo
5,LOG-4006,Cali,Tractomula,Electrónica,180.5,70.0,7.96,A Tiempo
7,LOG-4008,Ibagué,Camioneta,Alimentos,180.5,NaN,21.94,A Tiempo
...,...,...,...,...,...,...,...,...
985,LOG-4986,Pereira,Tractomula,Alimentos,120.0,22.0,18.43,Retrasado
989,LOG-4990,Ibagué,Furgón,Alimentos,180.5,NaN,13.30,A Tiempo
991,LOG-4992,Armenia,Camión Mediano,Materiales Construcción,120.0,NaN,22.40,A Tiempo
994,LOG-4995,Ibagué,Camión Mediano,Textiles,120.0,52.0,3.10,A Tiempo
998,LOG-4999,Manizales,Furgón,Textiles,180.5,22.0,21.51,A Tiempo

## 8. Consultas con el método .query()

In [91]:
# Envios originados en Pereira con Estado_Entrega Retrasado
df_pereira_retrasado = df_sin_duplicados.query('Ruta_Origen == "Pereira" and Estado_Entrega == "Retrasado"')
df_pereira_retrasado

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
9,LOG-4010,Pereira,Camión Mediano,Electrónica,78.5,8.5,10.56,Retrasado
35,LOG-4036,Pereira,Camioneta,Electrónica,78.5,14.0,13.01,Retrasado
62,LOG-4063,Pereira,Camión Mediano,Textiles,120.0,14.0,8.10,Retrasado
75,LOG-4076,Pereira,Camión Mediano,Electrónica,78.5,14.0,16.42,Retrasado
81,LOG-4082,Pereira,Tractomula,Alimentos,78.5,22.0,6.76,Retrasado
86,LOG-4087,Pereira,Furgón,Electrónica,NaN,22.0,10.19,Retrasado
93,LOG-4094,Pereira,Tractomula,Textiles,78.5,35.5,7.06,Retrasado
98,LOG-4099,Pereira,Camioneta,Electrónica,45.0,8.5,9.80,Retrasado
144,LOG-4145,Pereira,Tractomula,Alimentos,78.5,8.5,13.41,Retrasado
168,LOG-4169,Pereira,Furgón,Materiales Construcción,45.0,14.0,10.61,Retrasado
180,LOG-4181,Pereira,Furgón,Electrónica,180.5,8.5,14.90,Retrasado
199,LOG-4200,Pereira,Camión Mediano,Textiles,78.5,22.0,12.16,Retrasado
213,LOG-4214,Pereira,Tractomula,Textiles,310.0,52.0,13.65,Retrasado
255,LOG-4256,Pereira,Furgón,Alimentos,78.5,22.0,10.91,Retrasado
257,LOG-4258,Pereira,Furgón,Textiles,260.0,NaN,12.11,Retrasado
272,LOG-4273,Pereira,Tractomula,Electrónica,45.0,70.0,14.84,Retrasado
279,LOG-4280,Pereira,Furgón,Alimentos,78.5,22.0,10.56,Retrasado
289,LOG-4290,Pereira,Camión Mediano,Materiales Construcción,260.0,14.0,18.45,Retrasado
310,LOG-4311,Pereira,Tractomula,Textiles,180.5,14.0,1.96,Retrasado
312,LOG-4313,Pereira,Tractomula,Materiales Construcción,120.0,22.0,14.50,Retrasado
313,LOG-4314,Pereira,Camión Mediano,Alimentos,120.0,35.5,10.92,Retrasado
347,LOG-4348,Pereira,Camión Mediano,Textiles,NaN,52.0,19.70,Retrasado
364,LOG-4365,Pereira,Tractomula,Textiles,260.0,14.0,19.95,Retrasado
405,LOG-4406,Pereira,Camioneta,Electrónica,180.5,8.5,17.52,Retrasado
414,LOG-4415,Pereira,Camioneta,Materiales Construcción,180.5,22.0,13.84,Retrasado
423,LOG-4424,Pereira,Camioneta,Electrónica,180.5,NaN,9.83,Retrasado
460,LOG-4461,Pereira,Camión Mediano,Electrónica,78.5,70.0,19.60,Retrasado
479,LOG-4480,Pereira,Camioneta,Electrónica,180.5,22.0,10.45,Retrasado
511,LOG-4512,Pereira,Camioneta,Materiales Construcción,260.0,35.5,23.63,Retrasado
520,LOG-4521,Pereira,Tractomula,Alimentos,78.5,14.0,2.25,Retrasado
543,LOG-4544,Pereira,Tractomula,Electrónica,310.0,35.5,14.28,Retrasado
575,LOG-4576,Pereira,Camión Mediano,Alimentos,NaN,14.0,13.76,Retrasado
597,LOG-4598,Pereira,Camión Mediano,Electrónica,78.5,22.0,15.22,Retrasado
621,LOG-4622,Pereira,Camión Mediano,Electrónica,120.0,22.0,12.13,Retrasado
622,LOG-4623,Pereira,Camión Mediano,Textiles,180.5,14.0,23.45,Retrasado
623,LOG-4624,Pereira,Tractomula,Electrónica,120.0,8.5,0.61,Retrasado
629,LOG-4630,Pereira,Tractomula,Electrónica,180.5,14.0,16.17,Retrasado
634,LOG-4635,Pereira,Tractomula,Electrónica,180.5,35.5,22.40,Retrasado
643,LOG-4644,Pereira,Camioneta,Materiales Construcción,450.0,14.0,22.86,Retrasado
653,LOG-4654,Pereira,Camión Mediano,Electrónica,310.0,8.5,7.16,Retrasado
663,LOG-4664,Pereira,Camión Mediano,Materiales Construcción,180.5,35.5,12.73,Retrasado
690,LOG-4691,Pereira,Tractomula,Textiles,120.0,14.0,8.77,Retrasado
697,LOG-4698,Pereira,Furgón,Alimentos,78.5,8.5,21.39,Retrasado
707,LOG-4708,Pereira,Furgón,Textiles,120.0,8.5,16.10,Retrasado
714,LOG-4715,Pereira,Furgón,Textiles,120.0,14.0,19.61,Retrasado
749,LOG-4750,Pereira,Tractomula,Textiles,120.0,22.0,9.43,Retrasado
752,LOG-4753,Pereira,Furgón,Electrónica,180.5,8.5,24.66,Retrasado
758,LOG-4759,Pereira,Furgón,Textiles,180.5,22.0,20.33,Retrasado
801,LOG-4802,Pereira,Camioneta,Textiles,45.0,70.0,21.21,Retrasado
815,LOG-4816,Pereira,Camioneta,Materiales Construcción,78.5,52.0,17.34,Retrasado
832,LOG-4833,Pereira,Furgón,Materiales Construcción,120.0,22.0,13.79,Retrasado
870,LOG-4871,Pereira,Furgón,Alimentos,180.5,70.0,10.43,Retrasado
890,LOG-4891,Pereira,Camioneta,Electrónica,120.0,14.0,19.49,Retrasado
894,LOG-4895,Pereira,Furgón,Alimentos,180.5,70.0,9.06,Retrasado
901,LOG-4902,Pereira,Camión Mediano,Alimentos,180.5,35.5,20.99,Retrasado
911,LOG-4912,Pereira,Camioneta,Electrónica,310.0,22.0,3.63,Retrasado
913,LOG-4914,Pereira,Camioneta,Materiales Construcción,45.0,14.0,8.17,Retrasado
981,LOG-4982,Pereira,Furgón,Textiles,310.0,NaN,3.35,Retrasado
985,LOG-4986,Pereira,Tractomula,Alimentos,120.0,22.0,18.43,Retrasado

## 9. Filtrado lógico compuesto y cadenas

In [92]:
# Despachos A Tiempo y cuyo Tipo_Carga comience con la letra "E"
df_a_tiempo_e = df_sin_duplicados[
    (df_sin_duplicados["Estado_Entrega"] == "A Tiempo") &
    (df_sin_duplicados["Tipo_Carga"].str.startswith("E"))
]
df_a_tiempo_e

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.0,14.0,16.32,A Tiempo
5,LOG-4006,Cali,Tractomula,Electrónica,180.5,70.0,7.96,A Tiempo
11,LOG-4012,Cali,Furgón,Electrónica,45.0,14.0,11.18,A Tiempo
12,LOG-4013,Cali,Tractomula,Electrónica,180.5,8.5,8.72,A Tiempo
16,LOG-4017,Cali,Tractomula,Electrónica,45.0,14.0,18.18,A Tiempo
...,...,...,...,...,...,...,...,...
988,LOG-4989,Cali,Furgón,Electrónica,450.0,22.0,7.38,A Tiempo
990,LOG-4991,Pereira,Camioneta,Electrónica,78.5,14.0,1.88,A Tiempo
993,LOG-4994,Cali,Furgón,Electrónica,78.5,8.5,6.88,A Tiempo
995,LOG-4996,Armenia,Tractomula,Electrónica,450.0,14.0,1.01,A Tiempo
996,LOG-4997,Pereira,Camioneta,Electrónica,260.0,14.0,2.03,A Tiempo

## 10. Tratamiento e imputación de nulos

In [93]:
# Rellenar valores faltantes
df_faltantes = df_sin_duplicados.fillna(
    {
        "Distancia_KM": df_sin_duplicados["Distancia_KM"].mean(),
        "Combustible_Galones": 0.0
    }
)

df_faltantes

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.000000,14.0,16.32,A Tiempo
1,LOG-4002,Armenia,Camioneta,Textiles,120.000000,70.0,17.90,A Tiempo
2,LOG-4003,Ibagué,Camión Mediano,Alimentos,78.500000,22.0,5.64,A Tiempo
3,LOG-4004,Pereira,Camioneta,Textiles,157.267332,14.0,7.96,A Tiempo
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.000000,14.0,11.01,A Tiempo
...,...,...,...,...,...,...,...,...
995,LOG-4996,Armenia,Tractomula,Electrónica,450.000000,14.0,1.01,A Tiempo
996,LOG-4997,Pereira,Camioneta,Electrónica,260.000000,14.0,2.03,A Tiempo
997,LOG-4998,Ibagué,Camioneta,Alimentos,78.500000,52.0,20.68,Retrasado
998,LOG-4999,Manizales,Furgón,Textiles,180.500000,22.0,21.51,A Tiempo
999,LOG-5000,Ibagué,Tractomula,Materiales Construcción,45.000000,8.5,12.79,Retrasado

## 11. Columnas calculadas con .apply()

In [94]:
#Transformacion de datos
def obtener_categoria_carga(peso):
    if peso < 5.0:
        return "Ligero"
    elif peso <= 15.0:
        return "Intermedio"
    else:
        return "Pesado"

df_faltantes["Categoria_Carga"] = df_faltantes["Peso_Toneladas"].apply(obtener_categoria_carga)
df_faltantes

,ID_Envio,Ruta_Origen,Tipo_Vehiculo,Tipo_Carga,Distancia_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega,Categoria_Carga
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.000000,14.0,16.32,A Tiempo,Pesado
1,LOG-4002,Armenia,Camioneta,Textiles,120.000000,70.0,17.90,A Tiempo,Pesado
2,LOG-4003,Ibagué,Camión Mediano,Alimentos,78.500000,22.0,5.64,A Tiempo,Intermedio
3,LOG-4004,Pereira,Camioneta,Textiles,157.267332,14.0,7.96,A Tiempo,Intermedio
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.000000,14.0,11.01,A Tiempo,Intermedio
...,...,...,...,...,...,...,...,...,...
995,LOG-4996,Armenia,Tractomula,Electrónica,450.000000,14.0,1.01,A Tiempo,Ligero
996,LOG-4997,Pereira,Camioneta,Electrónica,260.000000,14.0,2.03,A Tiempo,Ligero
997,LOG-4998,Ibagué,Camioneta,Alimentos,78.500000,52.0,20.68,Retrasado,Pesado
998,LOG-4999,Manizales,Furgón,Textiles,180.500000,22.0,21.51,A Tiempo,Pesado
999,LOG-5000,Ibagué,Tractomula,Materiales Construcción,45.000000,8.5,12.79,Retrasado,Intermedio

## 12. Renombrado y reordenamiento

In [95]:
# Renombrar columnas
df_renombrado = df_faltantes.rename(
    columns={
        "Ruta_Origen": "Origen",
        "Distancia_KM": "Recorrido_KM"
    }
)
df_renombrado

,ID_Envio,Origen,Tipo_Vehiculo,Tipo_Carga,Recorrido_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega,Categoria_Carga
0,LOG-4001,Ibagué,Camión Mediano,Electrónica,120.000000,14.0,16.32,A Tiempo,Pesado
1,LOG-4002,Armenia,Camioneta,Textiles,120.000000,70.0,17.90,A Tiempo,Pesado
2,LOG-4003,Ibagué,Camión Mediano,Alimentos,78.500000,22.0,5.64,A Tiempo,Intermedio
3,LOG-4004,Pereira,Camioneta,Textiles,157.267332,14.0,7.96,A Tiempo,Intermedio
4,LOG-4005,Pereira,Tractomula,Materiales Construcción,120.000000,14.0,11.01,A Tiempo,Intermedio
...,...,...,...,...,...,...,...,...,...
995,LOG-4996,Armenia,Tractomula,Electrónica,450.000000,14.0,1.01,A Tiempo,Ligero
996,LOG-4997,Pereira,Camioneta,Electrónica,260.000000,14.0,2.03,A Tiempo,Ligero
997,LOG-4998,Ibagué,Camioneta,Alimentos,78.500000,52.0,20.68,Retrasado,Pesado
998,LOG-4999,Manizales,Furgón,Textiles,180.500000,22.0,21.51,A Tiempo,Pesado
999,LOG-5000,Ibagué,Tractomula,Materiales Construcción,45.000000,8.5,12.79,Retrasado,Intermedio

In [96]:
# Ordenar columnas
columnas_ordenadas = ["ID_Envio", "Categoria_Carga", "Origen", "Tipo_Vehiculo", "Tipo_Carga", "Recorrido_KM", "Combustible_Galones", "Peso_Toneladas", "Estado_Entrega"]
df_ordenado = df_renombrado[columnas_ordenadas]
df_ordenado

,ID_Envio,Categoria_Carga,Origen,Tipo_Vehiculo,Tipo_Carga,Recorrido_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
0,LOG-4001,Pesado,Ibagué,Camión Mediano,Electrónica,120.000000,14.0,16.32,A Tiempo
1,LOG-4002,Pesado,Armenia,Camioneta,Textiles,120.000000,70.0,17.90,A Tiempo
2,LOG-4003,Intermedio,Ibagué,Camión Mediano,Alimentos,78.500000,22.0,5.64,A Tiempo
3,LOG-4004,Intermedio,Pereira,Camioneta,Textiles,157.267332,14.0,7.96,A Tiempo
4,LOG-4005,Intermedio,Pereira,Tractomula,Materiales Construcción,120.000000,14.0,11.01,A Tiempo
...,...,...,...,...,...,...,...,...,...
995,LOG-4996,Ligero,Armenia,Tractomula,Electrónica,450.000000,14.0,1.01,A Tiempo
996,LOG-4997,Ligero,Pereira,Camioneta,Electrónica,260.000000,14.0,2.03,A Tiempo
997,LOG-4998,Pesado,Ibagué,Camioneta,Alimentos,78.500000,52.0,20.68,Retrasado
998,LOG-4999,Pesado,Manizales,Furgón,Textiles,180.500000,22.0,21.51,A Tiempo
999,LOG-5000,Intermedio,Ibagué,Tractomula,Materiales Construcción,45.000000,8.5,12.79,Retrasado

## 13. Agrupación y métricas globales

In [97]:
# Agrupar los datos por origen
grouped = df_ordenado.groupby("Origen")
grouped.groups

{'Armenia': [1, 6, 15, 17, 18, 19, 22, 23, 28, 29, 33, 34, 37, 42, 44, 46, 58, 67, 72, 80, 82, 88, 94, 113, 114, 115, 130, 141, 146, 147, 151, 158, 159, 160, 170, 173, 175, 177, 178, 179, 181, 189, 192, 194, 195, 196, 201, 204, 220, 223, 224, 229, 247, 251, 252, 259, 263, 287, 291, 295, 302, 311, 315, 321, 324, 333, 339, 343, 350, 351, 362, 365, 370, 372, 373, 379, 381, 384, 387, 388, 392, 394, 397, 398, 406, 407, 408, 410, 413, 415, 422, 440, 448, 468, 472, 474, 486, 495, 499, 504, ...], 'Cali': [5, 8, 11, 12, 13, 14, 16, 25, 30, 32, 40, 41, 60, 61, 63, 66, 70, 73, 74, 83, 90, 100, 101, 106, 117, 118, 122, 125, 128, 133, 138, 139, 142, 145, 152, 163, 165, 171, 183, 184, 186, 191, 200, 203, 206, 215, 219, 222, 225, 228, 230, 231, 237, 238, 240, 242, 245, 246, 253, 258, 262, 264, 265, 269, 273, 274, 278, 280, 283, 284, 293, 298, 300, 305, 317, 320, 323, 326, 328, 330, 332, 358, 361, 368, 382, 390, 400, 412, 419, 425, 430, 441, 451, 455, 457, 458, 467, 471, 476, 480, ...], 'Ibagué': [0, 2, 7, 20, 24, 27, 39, 51, 65, 68, 69, 87, 91, 95, 96, 109, 110, 111, 119, 120, 121, 129, 132, 135, 137, 140, 143, 161, 172, 187, 188, 193, 197, 202, 208, 209, 210, 217, 221, 232, 236, 243, 244, 249, 268, 270, 277, 288, 290, 294, 304, 307, 308, 314, 316, 319, 327, 329, 334, 349, 353, 357, 363, 366, 371, 377, 389, 391, 393, 396, 399, 401, 402, 403, 404, 416, 420, 424, 427, 431, 433, 437, 438, 439, 445, 446, 452, 454, 462, 463, 465, 485, 492, 500, 505, 506, 509, 512, 521, 526, ...], 'Manizales': [10, 26, 38, 43, 45, 48, 49, 50, 57, 71, 77, 78, 85, 92, 97, 99, 102, 103, 104, 105, 107, 123, 124, 126, 131, 134, 136, 149, 153, 155, 157, 162, 164, 166, 167, 169, 176, 182, 205, 211, 214, 218, 233, 235, 239, 250, 254, 256, 260, 261, 266, 271, 275, 281, 282, 285, 286, 296, 306, 309, 325, 331, 337, 341, 342, 346, 352, 359, 360, 367, 369, 374, 375, 376, 378, 383, 385, 409, 411, 418, 426, 429, 443, 449, 450, 459, 461, 464, 469, 473, 475, 477, 478, 481, 487, 488, 490, 493, 494, 496, ...], 'Pereira': [3, 4, 9, 21, 31, 35, 36, 47, 52, 53, 54, 55, 56, 59, 62, 64, 75, 76, 79, 81, 84, 86, 89, 93, 98, 108, 112, 116, 127, 144, 148, 150, 154, 156, 168, 174, 180, 185, 190, 198, 199, 207, 212, 213, 216, 226, 227, 234, 241, 248, 255, 257, 267, 272, 276, 279, 289, 292, 297, 299, 301, 303, 310, 312, 313, 318, 322, 335, 336, 338, 340, 344, 345, 347, 348, 354, 355, 356, 364, 380, 386, 395, 405, 414, 417, 421, 423, 428, 432, 434, 435, 436, 442, 444, 447, 453, 456, 460, 466, 470, ...]}

In [98]:
# Calcular el promedio de Recorrido_KM y la suma de Combustible_Galones
aggregate_data = grouped.agg(
    {
        "Recorrido_KM": "mean",
        "Combustible_Galones": "sum"
    }
)
aggregate_data

           Recorrido_KM  Combustible_Galones
Origen
Armenia      161.825700               4208.5
Cali         161.507856               5104.0
Ibagué       158.467885               5044.0
Manizales    153.644815               4201.0
Pereira      151.048322               4654.0

## 14. Dispersión con función personalizada

In [99]:
# Definir una funcion de agregacion personalizada
def rango(series):
    return series.max() - series.min()

# Agrupar los datos por tipo de vehiculo
grouped_vehiculo = df_ordenado.groupby("Tipo_Vehiculo")

# Aplicamos la funcion agg pero al grupo
aggregate_data_custom = grouped_vehiculo.agg(
    {
        "Peso_Toneladas": rango,
        "Recorrido_KM": rango
    }
)

aggregate_data_custom

                Peso_Toneladas  Recorrido_KM
Tipo_Vehiculo
Camioneta                24.47         405.0
Camión Mediano           24.23         405.0
Furgón                   24.18         405.0
Tractomula               24.46         405.0

## 15. Agrupamiento multinivel y consolidación

In [100]:
# Agrupar datos por origen y tipo de vehiculo
grouped_multi = df_ordenado.groupby(["Origen", "Tipo_Vehiculo"])
# Ver en tabla los envios de un grupo (Armenia y Tractomula)
grouped_multi.get_group(("Armenia", "Tractomula"))

,ID_Envio,Categoria_Carga,Origen,Tipo_Vehiculo,Tipo_Carga,Recorrido_KM,Combustible_Galones,Peso_Toneladas,Estado_Entrega
18,LOG-4019,Pesado,Armenia,Tractomula,Textiles,45.000000,35.5,23.68,Cancelado
19,LOG-4020,Intermedio,Armenia,Tractomula,Textiles,78.500000,22.0,12.91,Cancelado
72,LOG-4073,Pesado,Armenia,Tractomula,Textiles,78.500000,0.0,23.82,A Tiempo
114,LOG-4115,Pesado,Armenia,Tractomula,Electrónica,260.000000,14.0,20.02,A Tiempo
146,LOG-4147,Ligero,Armenia,Tractomula,Alimentos,45.000000,14.0,3.65,A Tiempo
159,LOG-4160,Intermedio,Armenia,Tractomula,Alimentos,78.500000,35.5,13.59,A Tiempo
177,LOG-4178,Intermedio,Armenia,Tractomula,Alimentos,180.500000,8.5,9.88,A Tiempo
181,LOG-4182,Pesado,Armenia,Tractomula,Alimentos,78.500000,35.5,18.00,Cancelado
194,LOG-4195,Pesado,Armenia,Tractomula,Textiles,450.000000,35.5,20.13,A Tiempo
224,LOG-4225,Pesado,Armenia,Tractomula,Electrónica,78.500000,14.0,22.12,Retrasado
247,LOG-4248,Pesado,Armenia,Tractomula,Alimentos,120.000000,14.0,15.90,A Tiempo
302,LOG-4303,Ligero,Armenia,Tractomula,Materiales Construcción,260.000000,14.0,4.92,Retrasado
343,LOG-4344,Pesado,Armenia,Tractomula,Electrónica,450.000000,14.0,17.27,A Tiempo
362,LOG-4363,Intermedio,Armenia,Tractomula,Textiles,45.000000,14.0,5.37,A Tiempo
373,LOG-4374,Pesado,Armenia,Tractomula,Textiles,120.000000,22.0,16.77,A Tiempo
379,LOG-4380,Pesado,Armenia,Tractomula,Alimentos,450.000000,8.5,17.17,Cancelado
388,LOG-4389,Ligero,Armenia,Tractomula,Electrónica,45.000000,22.0,3.92,A Tiempo
392,LOG-4393,Pesado,Armenia,Tractomula,Electrónica,120.000000,14.0,15.96,Retrasado
408,LOG-4409,Intermedio,Armenia,Tractomula,Electrónica,78.500000,35.5,11.42,Retrasado
486,LOG-4487,Intermedio,Armenia,Tractomula,Electrónica,450.000000,22.0,14.73,A Tiempo
499,LOG-4500,Pesado,Armenia,Tractomula,Materiales Construcción,78.500000,52.0,22.47,A Tiempo
561,LOG-4562,Pesado,Armenia,Tractomula,Textiles,78.500000,35.5,23.39,A Tiempo
570,LOG-4571,Ligero,Armenia,Tractomula,Alimentos,180.500000,8.5,2.02,A Tiempo
587,LOG-4588,Intermedio,Armenia,Tractomula,Materiales Construcción,260.000000,14.0,12.06,A Tiempo
631,LOG-4632,Intermedio,Armenia,Tractomula,Materiales Construcción,120.000000,8.5,7.98,A Tiempo
647,LOG-4648,Ligero,Armenia,Tractomula,Textiles,260.000000,35.5,2.54,Retrasado
702,LOG-4703,Pesado,Armenia,Tractomula,Materiales Construcción,120.000000,70.0,21.92,A Tiempo
709,LOG-4710,Pesado,Armenia,Tractomula,Electrónica,450.000000,8.5,16.67,A Tiempo
719,LOG-4720,Pesado,Armenia,Tractomula,Materiales Construcción,260.000000,0.0,15.85,Cancelado
739,LOG-4740,Pesado,Armenia,Tractomula,Alimentos,180.500000,14.0,21.30,Retrasado
740,LOG-4741,Pesado,Armenia,Tractomula,Alimentos,157.267332,8.5,21.01,Retrasado
763,LOG-4764,Ligero,Armenia,Tractomula,Textiles,45.000000,22.0,3.18,Retrasado
781,LOG-4782,Pesado,Armenia,Tractomula,Alimentos,260.000000,0.0,16.68,A Tiempo
788,LOG-4789,Intermedio,Armenia,Tractomula,Alimentos,45.000000,14.0,11.32,A Tiempo
791,LOG-4792,Pesado,Armenia,Tractomula,Electrónica,260.000000,22.0,17.73,A Tiempo
803,LOG-4804,Pesado,Armenia,Tractomula,Alimentos,78.500000,35.5,15.58,A Tiempo
898,LOG-4899,Pesado,Armenia,Tractomula,Textiles,120.000000,52.0,16.42,Retrasado
899,LOG-4900,Pesado,Armenia,Tractomula,Electrónica,78.500000,14.0,19.87,A Tiempo
933,LOG-4934,Pesado,Armenia,Tractomula,Textiles,260.000000,14.0,17.67,A Tiempo
935,LOG-4936,Pesado,Armenia,Tractomula,Alimentos,45.000000,52.0,17.56,A Tiempo
967,LOG-4968,Pesado,Armenia,Tractomula,Materiales Construcción,180.500000,22.0,19.92,A Tiempo
968,LOG-4969,Pesado,Armenia,Tractomula,Textiles,260.000000,8.5,15.80,A Tiempo
995,LOG-4996,Ligero,Armenia,Tractomula,Electrónica,450.000000,14.0,1.01,A Tiempo

In [101]:
# Calcular el promedio de Recorrido_KM y la suma de Peso_Toneladas por origen y tipo de vehiculo
aggregate_data_multi = grouped_multi.agg(
    {
        "Recorrido_KM": "mean",
        "Peso_Toneladas": "sum"
    }
)

aggregate_data_multi

                          Recorrido_KM  Peso_Toneladas
Origen    Tipo_Vehiculo
Armenia   Camioneta         151.864104          649.68
          Camión Mediano    157.800043          615.55
          Furgón            159.963135          528.35
          Tractomula        179.982961          631.18
Cali      Camioneta         176.832064          670.64
          Camión Mediano    157.508354          797.10
          Furgón            165.100693          613.00
          Tractomula        146.177376          572.45
Ibagué    Camioneta         152.716366          661.61
          Camión Mediano    162.655347          573.62
          Furgón            159.764852          735.43
          Tractomula        158.799270          513.16
Manizales Camioneta         166.192158          510.36
          Camión Mediano    136.366028          618.12
          Furgón            159.392540          702.91
          Tractomula        154.000642          728.95
Pereira   Camioneta         166.196400          733.53
          Camión Mediano    142.150693          678.32
          Furgón            142.727723          754.41
          Tractomula        152.170213          582.36